name: Send auto-email

on:
  schedule:
    - cron: '0 17 * * *' # 5:00 PM UTC, corresponding to 5:00 AM next day NZST (UTC+12)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }} # Assuming you've set DATABASE_URL as a secret in your GitHub repository
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }} # If you have an API key for Resend, you can add it as a secret

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node scripts/mail.mjs
