name: Vercel Production Deployment

env:
  VERCEL_PROJECT_ID: 'prj_ozVwIdKu1CrPRBfaJcwIFE7cjLFu' # Hardcoded project ID
  VERCEL_ORG_ID: 'team_dSnfxncbww1olUYH5gbmmn3d' # Hardcoded org ID
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  schedule:
    - cron: '5 17 * * *' # Every day at 5:05 AM NZ
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
